# Generated by Django 3.1.7 on 2021-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210316_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource_required',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_need', models.IntegerField()),
            ],
        ),
    ]
