# Generated by Django 3.1.7 on 2021-03-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resource_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resource_required',
        ),
    ]
