# Generated by Django 3.1.7 on 2021-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_resource_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=122, null=True)),
                ('student_id', models.CharField(max_length=122, null=True)),
                ('student_mail', models.CharField(max_length=122, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='faculty',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_id',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='facultyid',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='facultyname',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
