# Generated by Django 3.1.7 on 2021-04-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210418_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section_id',
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
