# Generated by Django 3.1.7 on 2021-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210418_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=122, null=True)),
            ],
        ),
    ]
