# Generated by Django 3.1.7 on 2021-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_booking_resource_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_booking',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=12),
        ),
    ]
