# Generated by Django 3.1.7 on 2021-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210419_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=12),
        ),
    ]
