# Generated by Django 3.1.7 on 2021-04-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_booking_section_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='facultyid',
        ),
    ]
