# Generated by Django 3.1.7 on 2021-04-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210420_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='facultyid',
            new_name='user',
        ),
    ]
