# Generated by Django 3.1.7 on 2021-04-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210420_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=122, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.main_section'),
        ),
    ]
