# Generated by Django 3.1.7 on 2021-04-27 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210426_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.section'),
        ),
        migrations.DeleteModel(
            name='main_section',
        ),
    ]
